export const WF_AREA_ONBOARDING_DEFINITION = {
  id: 'wf-area-onboarding',
  name: 'Area Onboarding & Daily Upload Monitor',
  description:
    'Starts when an area/HHAH onboarding is successful. It keeps the area intake cycle active, waits for expected HHAH uploads, and triggers missing-upload notifications when an HHAH has not uploaded within the 24-hour window.',
  trigger: {
    id: 'trigger-onboarding-success',
    type: 'onboarding_success',
  },
  conditions: {
    onboarding_successful: 'statistical area and expected HHAHs are configured',
    upload_received_within_24h: 'expected HHAH uploaded Excel + PDF ZIP within 24 hours',
    upload_missing_after_24h: 'expected HHAH did not upload within 24 hours',
    notification_sent: 'missing-upload notification was sent/logged for the HHAH',
  },
  steps: [
    {
      id: 'area-s1',
      actor: 'system',
      taskKey: 'area.onboardingSuccess',
      name: 'Onboarding Successful',
      description: 'Area/HHAH onboarding is complete; start the daily intake monitor.',
      condition: 'onboarding_successful',
      preReq: [],
    },
    {
      id: 'area-s2',
      actor: 'system',
      taskKey: 'area.monitorExpectedUploads',
      name: 'Monitor Expected HHAH Uploads',
      description: 'Track each expected HHAH in the selected micro/metro statistical area for the daily upload window.',
      preReq: ['area-s1'],
    },
    {
      id: 'area-s3',
      actor: 'system',
      taskKey: 'area.continueUploadWorkflow',
      name: 'Upload Trigger Continues Normally',
      description: 'When an HHAH uploads Excel + PDF ZIP, the existing wf7 upload workflow starts independently.',
      condition: 'upload_received_within_24h',
      preReq: ['area-s2'],
    },
    {
      id: 'area-s4',
      actor: 'system',
      taskKey: 'area.sendMissingUploadNotification',
      name: 'Notification Trigger — Missing Upload',
      description: 'If an expected HHAH does not upload within 24 hours, create the notification workflow/action.',
      condition: 'upload_missing_after_24h',
      preReq: ['area-s2'],
    },
    {
      id: 'area-s5',
      actor: 'system',
      taskKey: 'area.recordNotificationStatus',
      name: 'Record Notification Status',
      description: 'Log the email notification state while keeping the upload workflow independent for late uploads.',
      condition: 'notification_sent',
      preReq: ['area-s4'],
    },
  ],
};

export const WF7_DEFINITION = {
  id: 'wf7',
  name: 'Bulk Upload Patient & Order',
  description:
    'Ingest an uploaded Excel workbook and related order PDFs. For each patient-order row, parse Excel, use AI extraction when fields are missing, validate upload context, then create/update patient, admission object, episode object, and order records. A human reviews and confirms each assembled record.',
  trigger: {
    id: 'trigger-7',
    type: 'file_upload',
    inputs: {
      workbook: { accepted: ['.xlsx'] },
      pdfs: { accepted: ['.pdf'], required: false },
    },
  },
  loop: {
    over: 'patient_order_row',
    until: 'last patient & last order',
  },
  conditions: {
    excel_row_complete: 'required Excel fields exist for patient, admission object, episode object, order, and HHAH upload context',
    excel_row_incomplete: 'one or more required Excel fields are missing',
    ai_extraction_success: 'Gemini extracted missing values from order PDF',
    ai_extraction_fail: 'Gemini could not extract enough usable values',
    human_data_validated: 'human reviewed and confirmed extracted or manually filled data',
    upload_context_ready: 'HHAH upload context is present, so patient/order processing can continue',
    patient_exists: 'patient found by name + dob + mrn',
    patient_not_exists: 'patient not found by name + dob + mrn',
    patient_write_success: 'create/update patient, admission object, and episode object committed',
    patient_write_fail: 'create/update patient, admission object, and episode object failed',
    patient_retry_success: 'patient write succeeded on retry',
    patient_retry_fail: 'patient write still failing after retry',
    admission_dates_ready: 'SOC exists, so the admission object can be matched or created',
    admission_dates_missing: 'SOC is missing, so a human must add admission object dates',
    admission_ready: 'admission object is available after the patient write (by Start of Care)',
    admission_exists: 'admission object already existed and the order was attached to it',
    admission_created: 'a new admission object was created for the patient',
    episode_dates_ready: 'SOE and EOE exist, so the episode object can be matched or created',
    episode_dates_missing: 'SOE or EOE is missing, so a human must add episode object dates',
    episode_ready: 'episode object is available after the patient write (by SOE/EOE)',
    episode_exists: 'episode object already existed and the order was attached to it',
    episode_created: 'a new episode object was created in the admission object',
    order_exists: 'order found by orderno',
    order_not_exists: 'order not found by orderno',
    order_write_success: 'create/update order committed',
    order_write_fail: 'create/update order failed',
    order_retry_success: 'order write succeeded on retry',
    order_retry_fail: 'order write still failing after retry',
  },
  steps: [
    {
      id: 'wf7-s1',
      actor: 'system',
      taskKey: 'excel.parseWorkbook',
      name: 'Parse Excel Workbook',
      description: 'Read Sheet1 patient/admission object/episode object data and Sheet2 order data, then join rows by patientName + dob + mrn.',
      preReq: [],
    },
    {
      id: 'wf7-s2',
      actor: 'system',
      taskKey: 'row.checkCompleteness',
      name: 'Check Required Fields',
      description: 'Check whether required fields exist in the Excel row before DB checks begin.',
      preReq: ['wf7-s1'],
    },
    {
      id: 'wf7-s3',
      actor: 'ai',
      taskKey: 'ai.extractMissingDataFromPdf',
      name: 'Extract Missing Data From PDF',
      description: 'Use Gemini to extract missing patient/order/reference fields from the uploaded order PDFs.',
      condition: 'excel_row_incomplete',
      preReq: ['wf7-s2'],
    },
    {
      id: 'wf7-s4',
      actor: 'human',
      taskKey: 'human.validateExtractedData',
      name: 'Validate Extracted Data',
      description: 'Human validates or edits AI-extracted data before DB writes continue.',
      condition: 'ai_extraction_success',
      preReq: ['wf7-s3'],
    },
    {
      id: 'wf7-s5',
      actor: 'human',
      taskKey: 'human.fillMissingData',
      name: 'Manually Fill Missing Data',
      description: 'AI extraction failed or was incomplete, so a human fills the missing values.',
      condition: 'ai_extraction_fail',
      preReq: ['wf7-s3'],
    },
    {
      id: 'wf7-s12',
      actor: 'system',
      taskKey: 'refs.confirmUploadContext',
      name: 'Confirm HHAH Upload Context',
      description: 'Confirm the workflow has the HHAH/upload context needed before patient and order writes continue.',
      condition: 'upload_context_ready',
      preReq: ['wf7-s2', 'wf7-s4', 'wf7-s5'],
    },
    {
      id: 'wf7-s24',
      actor: 'system',
      taskKey: 'dates.checkAdmission',
      name: 'Check Admission Object Dates',
      description: 'Confirm SOC exists before admission object matching or creation.',
      preReq: ['wf7-s12'],
    },
    {
      id: 'wf7-s25',
      actor: 'human',
      taskKey: 'human.fillAdmissionDates',
      name: 'Manually Add Admission Object Dates',
      description: 'SOC is missing. Human adds admission object dates before the patient/admission object write continues.',
      condition: 'admission_dates_missing',
      preReq: ['wf7-s24'],
    },
    {
      id: 'wf7-s26',
      actor: 'system',
      taskKey: 'dates.checkEpisode',
      name: 'Check Episode Object Dates',
      description: 'Confirm SOE and EOE exist before episode object matching or creation.',
      preReq: ['wf7-s24', 'wf7-s25'],
    },
    {
      id: 'wf7-s27',
      actor: 'human',
      taskKey: 'human.fillEpisodeDates',
      name: 'Manually Add Episode Object Dates',
      description: 'SOE or EOE is missing. Human adds episode object dates before episode object matching or creation.',
      condition: 'episode_dates_missing',
      preReq: ['wf7-s26'],
    },
    {
      id: 'wf7-s13',
      actor: 'system',
      taskKey: 'patient.update',
      name: 'Update Patient',
      description: 'Patient found. Append or update admission object and episode object data.',
      condition: 'patient_exists',
      preReq: ['wf7-s26', 'wf7-s27'],
    },
    {
      id: 'wf7-s14',
      actor: 'system',
      taskKey: 'patient.create',
      name: 'Create Patient',
      description: 'Patient not found. Create patient with admission object and episode object data.',
      condition: 'patient_not_exists',
      preReq: ['wf7-s26', 'wf7-s27'],
    },
    {
      id: 'wf7-s15',
      actor: 'system',
      taskKey: 'patient.retryWrite',
      name: 'Retry Patient Write',
      description: 'Patient create/update failed. Retry once automatically.',
      condition: 'patient_write_fail',
      preReq: ['wf7-s13', 'wf7-s14'],
    },
    {
      id: 'wf7-s16',
      actor: 'human',
      taskKey: 'human.fixPatientWrite',
      name: 'Fix Patient Write',
      description: 'Patient write still failed after retry. Human fixes the patient/admission object/episode object record.',
      condition: 'patient_retry_fail',
      preReq: ['wf7-s15'],
    },
    {
      id: 'wf7-s17',
      actor: 'system',
      taskKey: 'order.update',
      name: 'Update Order',
      description: 'Order found. Update the existing order and linked admission object/episode object references.',
      condition: 'order_exists',
      preReq: ['wf7-s13', 'wf7-s14', 'wf7-s15', 'wf7-s16'],
    },
    {
      id: 'wf7-s18',
      actor: 'system',
      taskKey: 'order.create',
      name: 'Create Order',
      description: 'Order not found. Create order and link to patient, admission object, episode object, and HHAH context.',
      condition: 'order_not_exists',
      preReq: ['wf7-s13', 'wf7-s14', 'wf7-s15', 'wf7-s16'],
    },
    {
      id: 'wf7-s19',
      actor: 'system',
      taskKey: 'order.retryWrite',
      name: 'Retry Order Write',
      description: 'Order create/update failed. Retry once automatically.',
      condition: 'order_write_fail',
      preReq: ['wf7-s17', 'wf7-s18'],
    },
    {
      id: 'wf7-s20',
      actor: 'human',
      taskKey: 'human.fixOrderWrite',
      name: 'Fix Order Write',
      description: 'Order write still failed after retry. Human fixes the order record.',
      condition: 'order_retry_fail',
      preReq: ['wf7-s19'],
    },
    {
      id: 'wf7-s21',
      actor: 'human',
      taskKey: 'human.reviewRecord',
      name: 'Review & Confirm Record',
      description: 'Human reviews the assembled patient, admission object, episode object, order, and HHAH upload context.',
      preReq: ['wf7-s17', 'wf7-s18', 'wf7-s19', 'wf7-s20'],
    },
  ],
};

export const WF_SIGNING_DEFINITION = {
  id: 'wf-signing',
  name: 'Document Signing Follow-up',
  description:
    'Starts after the patient is created/updated and an order document is uploaded. It reviews document readiness, sends the document to the physician for signature, waits up to 48 hours, then updates signed status or sends an overdue email.',
  trigger: {
    id: 'trigger-order-document-ready',
    type: 'order_document_ready',
  },
  conditions: {
    document_ready_for_signing: 'document has the fields and PDF needed for signing',
    document_not_ready_for_signing: 'document is missing fields or PDF readiness checks',
    signed_within_48h: 'physician signed the document within 48 hours',
    signing_overdue: 'physician has not signed within 48 hours',
  },
  steps: [
    {
      id: 'sign-s1',
      actor: 'system',
      taskKey: 'signing.reviewReadiness',
      name: 'Review Document Readiness For Signing',
      description: 'Check whether the uploaded order PDF and order metadata are ready to send for signature.',
      preReq: [],
    },
    {
      id: 'sign-s2',
      actor: 'human',
      taskKey: 'signing.fixDocument',
      name: 'Manually Fix Document',
      description: 'Document is not ready for signing. A person fixes missing fields or PDF readiness issues.',
      condition: 'document_not_ready_for_signing',
      preReq: ['sign-s1'],
    },
    {
      id: 'sign-s3',
      actor: 'system',
      taskKey: 'signing.sendToPhysician',
      name: 'Send Document To Physician',
      description: 'Send the ready document to the physician for signature.',
      condition: 'document_ready_for_signing',
      preReq: ['sign-s1', 'sign-s2'],
    },
    {
      id: 'sign-s4',
      actor: 'system',
      taskKey: 'signing.checkSignedWithin48h',
      name: 'Check Signed Within 48 Hours',
      description: 'Check whether the physician signed the document before the 48-hour deadline.',
      preReq: ['sign-s3'],
    },
    {
      id: 'sign-s5',
      actor: 'system',
      taskKey: 'signing.updateOrderSigned',
      name: 'Update Order Status — Signed',
      description: 'Document was signed within 48 hours, so update the order status to signed.',
      condition: 'signed_within_48h',
      preReq: ['sign-s4'],
    },
    {
      id: 'sign-s6',
      actor: 'system',
      taskKey: 'signing.emailPhysicianReminder',
      name: 'Email Physician — Signature Overdue',
      description: 'Document was not signed within 48 hours, so send/log an email reminder to the physician.',
      condition: 'signing_overdue',
      preReq: ['sign-s4'],
    },
  ],
};

export const WORKFLOW_DEFINITIONS = [
  WF_AREA_ONBOARDING_DEFINITION,
  WF7_DEFINITION,
  WF_SIGNING_DEFINITION,
];

export const SEEDED_USERS = [
  { id: 'u1', name: 'Alice', jobRole: 'Operations', accessLevel: 'worker' },
  { id: 'u2', name: 'Bob', jobRole: 'Clinical Ops', accessLevel: 'worker' },
  { id: 'u3', name: 'Carol', jobRole: 'Billing Ops', accessLevel: 'worker' },
];
