export const WF7_DEFINITION = {
  id: 'wf7',
  name: 'Bulk Upload Patient & Order',
  description:
    'Ingest an uploaded Excel workbook and related order PDFs. For each patient-order row, parse Excel, use AI extraction when fields are missing, validate reference records, create missing references through human tasks, then create/update patient, admission, episode, and order records. A human reviews and confirms the assembled record before the next row continues.',
  trigger: {
    id: 'trigger-7',
    type: 'file_upload',
    inputs: {
      workbook: { accepted: ['.xlsx'] },
      pdfs: { accepted: ['.pdf'], required: false },
    },
  },
  loop: {
    over: 'patient_order_row',
    until: 'last patient & last order',
  },
  conditions: {
    excel_row_complete: 'required Excel fields exist for patient, admission, episode, order, PG, HHAH, and practitioner NPI',
    excel_row_incomplete: 'one or more required Excel fields are missing',
    ai_extraction_success: 'Gemini extracted missing values from order PDF',
    ai_extraction_fail: 'Gemini could not extract enough usable values',
    human_data_validated: 'human reviewed and confirmed extracted or manually filled data',
    practitioner_exists: 'practitioner with NPI exists in DB',
    practitioner_not_exists: 'practitioner with NPI does not exist in DB',
    pg_exists: 'physician group with name exists in DB',
    pg_not_exists: 'physician group with name does not exist in DB',
    pg_missing_blocks_patient: 'physician group is missing — patient creation is blocked and the row goes to human review',
    hhah_exists: 'home health agency with name exists in DB',
    hhah_not_exists: 'home health agency with name does not exist in DB',
    reference_records_ready: 'practitioner, PG, and HHAH are all available in DB',
    patient_exists: 'patient found by name + dob + mrn',
    patient_not_exists: 'patient not found by name + dob + mrn',
    patient_write_success: 'create/update patient, admission, and episode committed',
    patient_write_fail: 'create/update patient, admission, and episode failed',
    patient_retry_success: 'patient write succeeded on retry',
    patient_retry_fail: 'patient write still failing after retry',
    admission_ready: 'admission record exists for the patient (by Start of Care)',
    episode_ready: 'episode record exists in the admission (by SOE/EOE)',
    order_exists: 'order found by orderno',
    order_not_exists: 'order not found by orderno',
    order_write_success: 'create/update order committed',
    order_write_fail: 'create/update order failed',
    order_retry_success: 'order write succeeded on retry',
    order_retry_fail: 'order write still failing after retry',
  },
  steps: [
    {
      id: 'wf7-s1',
      actor: 'system',
      taskKey: 'excel.parseWorkbook',
      name: 'Parse Excel Workbook',
      description: 'Read Sheet1 patient/admission/episode data and Sheet2 order data, then join rows by patientName + dob + mrn.',
      preReq: [],
    },
    {
      id: 'wf7-s2',
      actor: 'system',
      taskKey: 'row.checkCompleteness',
      name: 'Check Required Fields',
      description: 'Check whether required fields exist in the Excel row before DB checks begin.',
      preReq: ['wf7-s1'],
    },
    {
      id: 'wf7-s3',
      actor: 'ai',
      taskKey: 'ai.extractMissingDataFromPdf',
      name: 'Extract Missing Data From PDF',
      description: 'Use Gemini to extract missing patient/order/reference fields from the uploaded order PDFs.',
      condition: 'excel_row_incomplete',
      preReq: ['wf7-s2'],
    },
    {
      id: 'wf7-s4',
      actor: 'human',
      taskKey: 'human.validateExtractedData',
      name: 'Validate Extracted Data',
      description: 'Human validates or edits AI-extracted data before DB writes continue.',
      condition: 'ai_extraction_success',
      preReq: ['wf7-s3'],
    },
    {
      id: 'wf7-s5',
      actor: 'human',
      taskKey: 'human.fillMissingData',
      name: 'Manually Fill Missing Data',
      description: 'AI extraction failed or was incomplete, so a human fills the missing values.',
      condition: 'ai_extraction_fail',
      preReq: ['wf7-s3'],
    },
    {
      id: 'wf7-s6',
      actor: 'system',
      taskKey: 'refs.checkPractitionerByNpi',
      name: 'Check Practitioner NPI',
      description: 'Check whether the practitioner NPI from the order exists in DB.',
      preReq: ['wf7-s2', 'wf7-s4', 'wf7-s5'],
    },
    {
      id: 'wf7-s7',
      actor: 'human',
      taskKey: 'human.createPractitioner',
      name: 'Create Practitioner',
      description: 'Practitioner NPI is missing in DB. Human validates details and creates the practitioner record.',
      condition: 'practitioner_not_exists',
      preReq: ['wf7-s6'],
    },
    {
      id: 'wf7-s8',
      actor: 'system',
      taskKey: 'refs.checkPgByName',
      name: 'Check Physician Group',
      description: 'Check whether the PG name from the patient row exists in DB.',
      preReq: ['wf7-s6', 'wf7-s7'],
    },
    {
      id: 'wf7-s9',
      actor: 'human',
      taskKey: 'human.reviewMissingPg',
      name: 'Review — Missing Physician Group',
      description: 'Physician Group is missing. Patient creation is BLOCKED. A human reviews the row and creates/adds the correct PG before the patient can be created.',
      condition: 'pg_not_exists',
      preReq: ['wf7-s8'],
    },
    {
      id: 'wf7-s12',
      actor: 'system',
      taskKey: 'refs.recheckAll',
      name: 'Confirm Reference Records',
      description: 'Confirm practitioner and PG are available before patient write (HHAH comes from the login context).',
      condition: 'reference_records_ready',
      preReq: ['wf7-s8', 'wf7-s9'],
    },
    {
      id: 'wf7-s13',
      actor: 'system',
      taskKey: 'patient.update',
      name: 'Update Patient',
      description: 'Patient found. Append or update admission and episode data.',
      condition: 'patient_exists',
      preReq: ['wf7-s12'],
    },
    {
      id: 'wf7-s14',
      actor: 'system',
      taskKey: 'patient.create',
      name: 'Create Patient',
      description: 'Patient not found. Create patient with admission and episode data.',
      condition: 'patient_not_exists',
      preReq: ['wf7-s12'],
    },
    {
      id: 'wf7-s15',
      actor: 'system',
      taskKey: 'patient.retryWrite',
      name: 'Retry Patient Write',
      description: 'Patient create/update failed. Retry once automatically.',
      condition: 'patient_write_fail',
      preReq: ['wf7-s13', 'wf7-s14'],
    },
    {
      id: 'wf7-s16',
      actor: 'human',
      taskKey: 'human.fixPatientWrite',
      name: 'Fix Patient Write',
      description: 'Patient write still failed after retry. Human fixes the patient/admission/episode record.',
      condition: 'patient_retry_fail',
      preReq: ['wf7-s15'],
    },
    {
      id: 'wf7-s22',
      actor: 'system',
      taskKey: 'admission.confirm',
      name: 'Create / Confirm Admission',
      description: 'Confirm the admission (matched by patient + Start of Care) created with the patient bundle.',
      condition: 'admission_ready',
      preReq: ['wf7-s13', 'wf7-s14', 'wf7-s15', 'wf7-s16'],
    },
    {
      id: 'wf7-s23',
      actor: 'system',
      taskKey: 'episode.confirm',
      name: 'Create / Confirm Episode',
      description: 'Confirm the episode within the admission (matched by SOE/EOE — reused if it exists, else created) before the order is attached.',
      condition: 'episode_ready',
      preReq: ['wf7-s22'],
    },
    {
      id: 'wf7-s17',
      actor: 'system',
      taskKey: 'order.update',
      name: 'Update Order',
      description: 'Order found. Update the existing order and linked admission/episode references.',
      condition: 'order_exists',
      preReq: ['wf7-s23'],
    },
    {
      id: 'wf7-s18',
      actor: 'system',
      taskKey: 'order.create',
      name: 'Create Order',
      description: 'Order not found. Create order and link to patient, admission, episode, PG, HHAH, and practitioner.',
      condition: 'order_not_exists',
      preReq: ['wf7-s23'],
    },
    {
      id: 'wf7-s19',
      actor: 'system',
      taskKey: 'order.retryWrite',
      name: 'Retry Order Write',
      description: 'Order create/update failed. Retry once automatically.',
      condition: 'order_write_fail',
      preReq: ['wf7-s17', 'wf7-s18'],
    },
    {
      id: 'wf7-s20',
      actor: 'human',
      taskKey: 'human.fixOrderWrite',
      name: 'Fix Order Write',
      description: 'Order write still failed after retry. Human fixes the order record.',
      condition: 'order_retry_fail',
      preReq: ['wf7-s19'],
    },
    {
      id: 'wf7-s21',
      actor: 'human',
      taskKey: 'human.reviewRecord',
      name: 'Review & Confirm Record',
      description: 'Human reviews the assembled patient, admission, episode, order, practitioner, PG, and HHAH data.',
      preReq: ['wf7-s17', 'wf7-s18', 'wf7-s19', 'wf7-s20'],
    },
  ],
};

export const SEEDED_USERS = [
  { id: 'u1', name: 'Alice', jobRole: 'Operations', accessLevel: 'worker' },
  { id: 'u2', name: 'Bob', jobRole: 'Clinical Ops', accessLevel: 'worker' },
  { id: 'u3', name: 'Carol', jobRole: 'Billing Ops', accessLevel: 'worker' },
];
