import { connect } from './cdp.mjs';
import { injectSetters, setBanner } from './cdp-extra.mjs';
const p = await connect({ port: 9222 });
await p.send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 800, deviceScaleFactor: 1, mobile: false });
await p.navigate('http://localhost:8791/builder/workflows');
await new Promise(r => setTimeout(r, 2500));
await injectSetters(p);
await setBanner(p, 'Smoke test banner', 'checking layout offset');
await new Promise(r => setTimeout(r, 400));
const txt = await p.evaluate('document.body.innerText.slice(0, 1200)');
console.log('BODY_HEAD:', JSON.stringify(txt.slice(0, 600)));
const hasPhase = await p.evaluate("document.body.innerText.includes('Phase 1')");
const hasFor = await p.evaluate("document.body.innerText.includes('For each onboarded agency')");
const views = await p.evaluate("[...document.querySelectorAll('button')].filter(b=>/View/i.test(b.textContent||'')).length");
console.log('hasPhase1:', hasPhase, 'hasForEach:', hasFor, 'viewButtons:', views);
await p.send('Page.captureScreenshot', { format: 'png' }).then(({data}) => { import('node:fs').then(fs => fs.writeFileSync('/tmp/smoke.png', Buffer.from(data,'base64'))); });
await new Promise(r => setTimeout(r, 300));
p.close();
process.exit(0);
